// <auto-generated />
namespace TaskApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitilizationDatabases : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitilizationDatabases));
        
        string IMigrationMetadata.Id
        {
            get { return "202003131049392_InitilizationDatabases"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
